apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: posthook-job
  namespace: acm-application-deploy-test
spec:
  tower_auth_secret: aap
  job_template_name: Posthook Demo Job Template
  extra_vars:
    cost: 6.88
    ghosts: ["inky","pinky","clyde","sue"]
    is_enable: false
    other_variable: foo
    pacman: mrs
    size: 8
    targets_list:
    - aaa
    - bbb
    - ccc
    version: 1.23.45
